### ISSUE TITLE
Can't run inspect with just a filename

### ISSUE THREAD

**Issue by RoryStokes** [agiledigital/toolform#25]
`toolform inspect -i ./environment.conf` (or any relative path) works fine, but `toolform inspect -i environment.conf` seems to fail to follow include statements :
```toolform inspect -i environment.conf
Failed due to the following errors:
Failed to read project: [[id] Key not found. @ (file:/.../environment.conf:1):
[name] Key not found. @ (file:/.../environment.conf:1):
[components] Key not found. @ (file:/.../environment.conf:1):
[resources] Key not found. @ (file:/.../environment.conf:1):
[topology] Key not found. @ (file:/.../environment.conf:1)]
```
(where I've replaced the full path with `...`)

**Comment by RoryStokes** [comment]
Looks like the same error on input for generate commands, and a null pointer exception for output on generate commands:
```$ toolform generate minishift -i ./environment.conf -o test.yml
Exception in thread "main" java.lang.NullPointerException
	at au.com.agiledigital.toolform.command.generate.kubernetes.minishift.GenerateMinishiftCommand.execute(GenerateMinishiftCommand.scala:47)
	at au.com.agiledigital.toolform.command.generate.kubernetes.minishift.GenerateMinishiftCommand.$anonfun$command$1(GenerateMinishiftCommand.scala:37)
```
